'use server'

/**
 * Auth Server Actions
 * Magic link authentication, sign out, profile creation
 */

import { createClient } from '@/lib/supabase/server'
import { redirect } from 'next/navigation'
import { revalidatePath } from 'next/cache'
import type { ProfileInsert } from '@/types'

export type AuthResult = {
  success: boolean
  error?: string
  message?: string
}

/**
 * Send magic link to email
 */
export async function signInWithMagicLink(
  email: string,
  redirectTo?: string
): Promise<AuthResult> {
  const supabase = await createClient()

  const { error } = await supabase.auth.signInWithOtp({
    email,
    options: {
      emailRedirectTo: redirectTo || `${process.env.NEXT_PUBLIC_APP_URL}/auth/callback`,
    },
  })

  if (error) {
    return {
      success: false,
      error: error.message,
    }
  }

  return {
    success: true,
    message: 'Check your email for the magic link!',
  }
}

/**
 * Sign out current user
 */
export async function signOut(): Promise<void> {
  const supabase = await createClient()

  await supabase.auth.signOut()

  revalidatePath('/', 'layout')
  redirect('/')
}

/**
 * Get current authenticated user
 */
export async function getCurrentUser() {
  const supabase = await createClient()

  const { data: { user }, error } = await supabase.auth.getUser()

  if (error || !user) {
    return null
  }

  return user
}

/**
 * Get current user's profile
 */
export async function getCurrentProfile() {
  const supabase = await createClient()

  const { data: { user } } = await supabase.auth.getUser()

  if (!user) {
    return null
  }

  const { data: profile, error } = await supabase
    .from('profiles')
    .select('*')
    .eq('id', user.id)
    .single()

  if (error) {
    // Profile might not exist yet
    return null
  }

  return profile
}

/**
 * Create or update user profile
 * Called after auth to ensure profile exists
 */
export async function ensureProfile(): Promise<AuthResult> {
  const supabase = await createClient()

  const { data: { user } } = await supabase.auth.getUser()

  if (!user) {
    return {
      success: false,
      error: 'Not authenticated',
    }
  }

  // Check if profile exists
  const { data: existingProfile } = await supabase
    .from('profiles')
    .select('id')
    .eq('id', user.id)
    .single()

  if (existingProfile) {
    return {
      success: true,
      message: 'Profile already exists',
    }
  }

  // Create new profile
  const profileData: ProfileInsert = {
    id: user.id,
    email: user.email,
    // handle will be auto-generated by trigger
  }

  const { error } = await supabase
    .from('profiles')
    .insert(profileData)

  if (error) {
    return {
      success: false,
      error: error.message,
    }
  }

  revalidatePath('/', 'layout')

  return {
    success: true,
    message: 'Profile created',
  }
}

/**
 * Update user profile
 */
export async function updateProfile(
  updates: { display_name?: string; phone?: string; avatar_url?: string }
): Promise<AuthResult> {
  const supabase = await createClient()

  const { data: { user } } = await supabase.auth.getUser()

  if (!user) {
    return {
      success: false,
      error: 'Not authenticated',
    }
  }

  const { error } = await supabase
    .from('profiles')
    .update(updates)
    .eq('id', user.id)

  if (error) {
    return {
      success: false,
      error: error.message,
    }
  }

  revalidatePath('/', 'layout')

  return {
    success: true,
    message: 'Profile updated',
  }
}

/**
 * Delete user account and all associated data
 */
export async function deleteAccount(): Promise<AuthResult> {
  const supabase = await createClient()

  const { data: { user } } = await supabase.auth.getUser()

  if (!user) {
    return {
      success: false,
      error: 'Not authenticated',
    }
  }

  // Delete profile (cascades to sessions, conversations, etc.)
  const { error: profileError } = await supabase
    .from('profiles')
    .delete()
    .eq('id', user.id)

  if (profileError) {
    return {
      success: false,
      error: profileError.message,
    }
  }

  // Sign out
  await supabase.auth.signOut()

  return {
    success: true,
    message: 'Account deleted',
  }
}
