export type V2CapabilityStatus = 'active' | 'locked' | 'read_only';

export type V2Capability = {
  actionType: string;
  toolName: string;
  label: string;
  category: string;
  status: V2CapabilityStatus;
  approvalRequired: boolean;
  approvalRequestable: boolean;
  endpoint: string | null;
  summary: string;
  requirements: string[];
  externalAction: boolean;
};

export const V2_CAPABILITIES: V2Capability[] = [
  {
    actionType: 'approval_request',
    toolName: 'approval_request',
    label: 'Approval request',
    category: 'Control Plane',
    status: 'active',
    approvalRequired: false,
    approvalRequestable: false,
    endpoint: '/api/actions/approvals',
    summary: 'Creates an approval card before any V2 write/action.',
    requirements: ['signed-in user', 'action summary', 'valid action type'],
    externalAction: false
  },
  {
    actionType: 'approval_status',
    toolName: 'approval_status',
    label: 'Approval status',
    category: 'Control Plane',
    status: 'active',
    approvalRequired: false,
    approvalRequestable: false,
    endpoint: '/api/actions/approvals',
    summary: 'Approves, denies, or cancels requested action cards.',
    requirements: ['signed-in user', 'requested approval owned by user'],
    externalAction: false
  },
  {
    actionType: 'action_audit_log',
    toolName: 'action_audit_log',
    label: 'Action audit log',
    category: 'Control Plane',
    status: 'active',
    approvalRequired: false,
    approvalRequestable: false,
    endpoint: '/api/actions/audit',
    summary: 'Reads user-owned audit history. Audit writes are server/trigger controlled.',
    requirements: ['signed-in user'],
    externalAction: false
  },
  {
    actionType: 'task_write',
    toolName: 'task_write',
    label: 'Task write',
    category: 'Personal Ops',
    status: 'active',
    approvalRequired: true,
    approvalRequestable: true,
    endpoint: '/api/tasks',
    summary: 'Creates or updates user-owned tasks after approval.',
    requirements: ['signed-in user', 'approved task_write approval'],
    externalAction: false
  },
  {
    actionType: 'cron_schedule_create',
    toolName: 'cron_schedule_create',
    label: 'In-app report schedule',
    category: 'Personal Ops',
    status: 'active',
    approvalRequired: true,
    approvalRequestable: true,
    endpoint: '/api/reports/schedules',
    summary: 'Creates in-app report schedules only. No email or external delivery.',
    requirements: ['signed-in user', 'approved cron_schedule_create approval'],
    externalAction: false
  },
  {
    actionType: 'daily_report_send',
    toolName: 'daily_report_send',
    label: 'Store daily report',
    category: 'Personal Ops',
    status: 'active',
    approvalRequired: true,
    approvalRequestable: true,
    endpoint: '/api/reports/daily',
    summary: 'Stores a daily report in-app. It does not send messages or email.',
    requirements: ['signed-in user', 'approved daily_report_send approval'],
    externalAction: false
  },
  {
    actionType: 'self_report_create',
    toolName: 'self_report_create',
    label: 'Create self-report',
    category: 'Ops',
    status: 'active',
    approvalRequired: true,
    approvalRequestable: true,
    endpoint: '/api/reports/daily',
    summary: 'Stores a truthful in-app self-report after approval.',
    requirements: ['signed-in user', 'approved self_report_create approval'],
    externalAction: false
  },
  {
    actionType: 'diagnostics_run',
    toolName: 'diagnostics_run',
    label: 'Diagnostics run',
    category: 'Ops',
    status: 'read_only',
    approvalRequired: false,
    approvalRequestable: false,
    endpoint: '/api/diagnostics',
    summary: 'Reads app/provider health and returns recommendations. It does not repair or mutate production.',
    requirements: ['server diagnostics endpoint'],
    externalAction: false
  },
  {
    actionType: 'browser_control',
    toolName: 'browser_control',
    label: 'Browser control container',
    category: 'Browser',
    status: 'active',
    approvalRequired: false,
    approvalRequestable: false,
    endpoint: '/api/actions/execute',
    summary: 'Creates the approved, audited, user-visible container for browser workflows. It does not run hidden automation.',
    requirements: ['signed-in user', 'approval card for each browser action', 'browser session audit trail'],
    externalAction: false
  },
  {
    actionType: 'browser_open',
    toolName: 'browser_open',
    label: 'Browser open',
    category: 'Browser',
    status: 'active',
    approvalRequired: true,
    approvalRequestable: true,
    endpoint: '/api/actions/execute',
    summary: 'Opens an isolated browser-control session container after explicit approval.',
    requirements: ['browser_control active', 'approved browser_open approval', 'http/https URL', 'session isolation'],
    externalAction: true
  },
  {
    actionType: 'browser_click',
    toolName: 'browser_click',
    label: 'Browser click',
    category: 'Browser',
    status: 'active',
    approvalRequired: true,
    approvalRequestable: true,
    endpoint: '/api/actions/execute',
    summary: 'Records an approved click inside an active isolated browser session container.',
    requirements: ['browser_control active', 'active browser_session_id', 'approved browser_click approval', 'audit log'],
    externalAction: true
  },
  {
    actionType: 'browser_type',
    toolName: 'browser_type',
    label: 'Browser type',
    category: 'Browser',
    status: 'active',
    approvalRequired: true,
    approvalRequestable: true,
    endpoint: '/api/actions/execute',
    summary: 'Records approved text entry intent after showing the data that would be typed.',
    requirements: ['browser_control active', 'active browser_session_id', 'field preview', 'approved browser_type approval'],
    externalAction: true
  },
  {
    actionType: 'browser_extract',
    toolName: 'browser_extract',
    label: 'Browser extract',
    category: 'Browser',
    status: 'active',
    approvalRequired: true,
    approvalRequestable: true,
    endpoint: '/api/actions/execute',
    summary: 'Records approved extraction intent with source/session tracking. No hidden page read occurs in this foundation.',
    requirements: ['browser_control active', 'active browser_session_id', 'approved browser_extract approval', 'source description'],
    externalAction: true
  },
  {
    actionType: 'browser_screenshot',
    toolName: 'browser_screenshot',
    label: 'Browser screenshot',
    category: 'Browser',
    status: 'active',
    approvalRequired: true,
    approvalRequestable: true,
    endpoint: '/api/actions/execute',
    summary: 'Records approved screenshot intent with session tracking. No image capture occurs until a visible runtime is attached.',
    requirements: ['browser_control active', 'active browser_session_id', 'approved browser_screenshot approval', 'retention controls'],
    externalAction: true
  },
  {
    actionType: 'browser_act',
    toolName: 'browser_act',
    label: 'Browser act',
    category: 'Browser',
    status: 'active',
    approvalRequired: true,
    approvalRequestable: true,
    endpoint: '/api/actions/execute',
    summary: 'Runs one approved Stagehand natural-language browser action inside an active isolated session.',
    requirements: ['browser_control active', 'active browser_session_id', 'approved browser_act approval', 'audit log'],
    externalAction: true
  },
  {
    actionType: 'browser_close',
    toolName: 'browser_close',
    label: 'Stop browser session',
    category: 'Browser',
    status: 'active',
    approvalRequired: false,
    approvalRequestable: false,
    endpoint: '/api/actions/execute',
    summary: 'Stops an active browser-control session using the session approval record and writes an audit entry.',
    requirements: ['active browser_session_id', 'session-owned approval record', 'audit log'],
    externalAction: false
  },
  {
    actionType: 'browser_demo',
    toolName: 'browser_demo',
    label: 'Browser demo workflow',
    category: 'Browser',
    status: 'active',
    approvalRequired: true,
    approvalRequestable: true,
    endpoint: '/api/actions/browser-demo',
    summary: 'Runs the safe example.com Stagehand workflow end to end with extraction, screenshot receipt, audit, and auto-close.',
    requirements: ['signed-in user', 'approved browser_demo approval', 'example.com allowlist', 'signed screenshot receipt'],
    externalAction: true
  },
  {
    actionType: 'job_apply',
    toolName: 'job_apply',
    label: 'Job apply workflow',
    category: 'Job Hunt',
    status: 'active',
    approvalRequired: true,
    approvalRequestable: true,
    endpoint: '/api/actions/job-apply',
    summary: 'Runs the approved job-apply container. Platform scripts stop at the review screen; the user must press the final submit button.',
    requirements: ['signed-in user', 'approved job_apply approval', 'active platform flag', 'persistent browser session', 'stop-before-submit gate'],
    externalAction: true
  },
  {
    actionType: 'linkedin_automation',
    toolName: 'linkedin_automation',
    label: 'LinkedIn automation',
    category: 'Hard Stop',
    status: 'locked',
    approvalRequired: true,
    approvalRequestable: false,
    endpoint: null,
    summary: 'Locked until a provider-compliant, user-visible workflow is approved.',
    requirements: ['compliance review', 'explicit approval boundary'],
    externalAction: true
  },
  {
    actionType: 'payment',
    toolName: 'payment',
    label: 'Payment action',
    category: 'Hard Stop',
    status: 'locked',
    approvalRequired: true,
    approvalRequestable: false,
    endpoint: null,
    summary: 'Hard-stopped. Payments, billing, and checkout actions cannot run in this browser container.',
    requirements: ['not configurable in V2'],
    externalAction: true
  },
  {
    actionType: 'send_email',
    toolName: 'send_email',
    label: 'Send email',
    category: 'Hard Stop',
    status: 'locked',
    approvalRequired: true,
    approvalRequestable: false,
    endpoint: null,
    summary: 'Hard-stopped. CubiQo may draft email later, but autonomous sending is blocked.',
    requirements: ['not configurable in V2'],
    externalAction: true
  },
  {
    actionType: 'social_post_publish',
    toolName: 'social_post_publish',
    label: 'Autonomous social publish',
    category: 'Hard Stop',
    status: 'locked',
    approvalRequired: true,
    approvalRequestable: false,
    endpoint: null,
    summary: 'Hard-stopped. Queued drafts can be approved later; autonomous publish is blocked.',
    requirements: ['not configurable in V2'],
    externalAction: true
  },
  {
    actionType: 'deploy',
    toolName: 'deploy',
    label: 'Deploy',
    category: 'Hard Stop',
    status: 'locked',
    approvalRequired: true,
    approvalRequestable: false,
    endpoint: null,
    summary: 'Hard-stopped. Browser automation cannot deploy or mutate QA/prod environments.',
    requirements: ['not configurable in V2'],
    externalAction: true
  },
  {
    actionType: 'job_profile_write',
    toolName: 'job_profile_write',
    label: 'Job profile write',
    category: 'Job Hunt',
    status: 'active',
    approvalRequired: true,
    approvalRequestable: true,
    endpoint: '/api/actions/execute',
    summary: 'Creates or updates the user-owned job profile after a preview card is approved.',
    requirements: ['signed-in user', 'approved job_profile_write approval', 'profile diff/preview card', 'server-side write boundary'],
    externalAction: false
  },
  {
    actionType: 'job_search_save',
    toolName: 'job_search_save',
    label: 'Job search save',
    category: 'Job Hunt',
    status: 'active',
    approvalRequired: true,
    approvalRequestable: true,
    endpoint: '/api/actions/execute',
    summary: 'Saves extracted LinkedIn, Indeed, or Dice job listings into user-owned Supabase state after approval.',
    requirements: ['browser_control active', 'approved job_search_save approval', 'LinkedIn/Indeed/Dice listing payload', 'server-side write boundary'],
    externalAction: false
  },
  {
    actionType: 'job_application_prepare',
    toolName: 'job_application_prepare',
    label: 'Application prepare',
    category: 'Job Hunt',
    status: 'active',
    approvalRequired: true,
    approvalRequestable: true,
    endpoint: '/api/actions/execute',
    summary: 'Creates a review card showing the exact job application payload before any submission action can run.',
    requirements: ['browser_control active', 'saved job listing', 'approved job_application_prepare approval', 'review payload preview'],
    externalAction: false
  },
  {
    actionType: 'job_application_submit_approved',
    toolName: 'job_application_submit_approved',
    label: 'Submit job application',
    category: 'Job Hunt',
    status: 'active',
    approvalRequired: true,
    approvalRequestable: true,
    endpoint: '/api/actions/execute',
    summary: 'Approves a prepared application package for user-visible submission. It never auto-submits to external job boards.',
    requirements: ['browser_control active', 'prepared review card', 'approved job_application_submit_approved approval', 'audit log'],
    externalAction: true
  },
  {
    actionType: 'resume_version_write',
    toolName: 'resume_version_write',
    label: 'Resume version write',
    category: 'Job Hunt',
    status: 'active',
    approvalRequired: true,
    approvalRequestable: true,
    endpoint: '/api/actions/execute',
    summary: 'Appends a named resume version after a diff/preview card is approved. Existing versions are never overwritten.',
    requirements: ['signed-in user', 'approved resume_version_write approval', 'resume diff/preview card', 'append-only storage'],
    externalAction: false
  },
  {
    actionType: 'pod_design_brief_create',
    toolName: 'pod_design_brief_create',
    label: 'POD design brief',
    category: 'Business/POD',
    status: 'active',
    approvalRequired: true,
    approvalRequestable: true,
    endpoint: '/api/actions/execute',
    summary: 'Saves a structured POD creative brief to user-owned Supabase state after approval.',
    requirements: ['signed-in user', 'approved pod_design_brief_create approval', 'creative preview card', 'server-side write boundary'],
    externalAction: false
  },
  {
    actionType: 'gfxtools_job_create',
    toolName: 'gfxtools_job_create',
    label: 'GFXTools job create',
    category: 'Business/POD',
    status: 'active',
    approvalRequired: true,
    approvalRequestable: true,
    endpoint: '/api/actions/execute',
    summary: 'Submits an approved creative brief to the server-side GFXTools connector when configured and stores a structured asset record.',
    requirements: ['signed-in user', 'approved gfxtools_job_create approval', 'GFXTools payload preview card', 'server-side connector status check', 'asset status record'],
    externalAction: true
  },
  {
    actionType: 'gfxtools_asset_resize',
    toolName: 'gfxtools_asset_resize',
    label: 'GFXTools asset resize',
    category: 'Business/POD',
    status: 'active',
    approvalRequired: true,
    approvalRequestable: true,
    endpoint: '/api/actions/execute',
    summary: 'Generates platform-sized variants for a ready GFXTools asset and emits an asset_ready event for the social pipeline.',
    requirements: ['signed-in user', 'approved gfxtools_asset_resize approval', 'ready GFX asset', 'platform variant output', 'asset_ready event'],
    externalAction: true
  },
  {
    actionType: 'gfxtools_connector_status',
    toolName: 'gfxtools_connector_status',
    label: 'GFXTools status',
    category: 'Business/POD',
    status: 'read_only',
    approvalRequired: false,
    approvalRequestable: false,
    endpoint: '/api/actions/execute',
    summary: 'Read-only server-side connector state. Missing credentials return disconnected; present credentials return configured_unverified until real provider verification exists.',
    requirements: ['server-side credential check only', 'no frontend key exposure', 'no fake connected state'],
    externalAction: false
  },
  {
    actionType: 'shopify_connector_status',
    toolName: 'shopify_connector_status',
    label: 'Shopify status',
    category: 'Business/POD',
    status: 'read_only',
    approvalRequired: false,
    approvalRequestable: false,
    endpoint: '/api/actions/execute',
    summary: 'Read-only server-side connector state. Missing credentials return disconnected; present credentials return configured_unverified until real Shopify verification exists.',
    requirements: ['server-side credential check only', 'no frontend key exposure', 'no fake connected state'],
    externalAction: false
  },
  {
    actionType: 'shopify_product_prepare',
    toolName: 'shopify_product_prepare',
    label: 'Shopify product prepare',
    category: 'Business/POD',
    status: 'active',
    approvalRequired: true,
    approvalRequestable: true,
    endpoint: '/api/actions/execute',
    summary: 'Builds an approved Shopify product payload from a ready GFXTools asset. Missing credentials block creation instead of faking connection.',
    requirements: ['signed-in user', 'approved shopify_product_prepare approval', 'ready GFX asset', 'full product preview card', 'server-side connector status check'],
    externalAction: true
  },
  {
    actionType: 'printify_connector_status',
    toolName: 'printify_connector_status',
    label: 'Printify status',
    category: 'Business/POD',
    status: 'read_only',
    approvalRequired: false,
    approvalRequestable: false,
    endpoint: '/api/actions/execute',
    summary: 'Read-only server-side connector state. Missing credentials return disconnected; present credentials return configured_unverified until real Printify verification exists.',
    requirements: ['server-side credential check only', 'no frontend key exposure', 'no fake connected state'],
    externalAction: false
  },
  {
    actionType: 'printify_design_prepare',
    toolName: 'printify_design_prepare',
    label: 'Printify design prepare',
    category: 'Business/POD',
    status: 'active',
    approvalRequired: true,
    approvalRequestable: true,
    endpoint: '/api/actions/execute',
    summary: 'Builds an approved Printify design/template payload from a ready GFXTools asset. Missing credentials block submission instead of faking connection.',
    requirements: ['signed-in user', 'approved printify_design_prepare approval', 'ready GFX asset', 'full design preview card', 'server-side connector status check'],
    externalAction: true
  },
  {
    actionType: 'shopify_store_connect',
    toolName: 'shopify_store_connect',
    label: 'Connect Shopify store',
    category: 'Business/POD',
    status: 'active',
    approvalRequired: true,
    approvalRequestable: true,
    endpoint: '/api/actions/execute',
    summary: 'Validates and stores Shopify credentials server-side only. The default store target is carlophillips.myshopify.com.',
    requirements: ['signed-in user', 'approved connection preview', 'server-side encryption key', 'Shopify private app/admin API key'],
    externalAction: true
  },
  {
    actionType: 'shopify_store_status',
    toolName: 'shopify_store_status',
    label: 'Shopify store status',
    category: 'Business/POD',
    status: 'read_only',
    approvalRequired: false,
    approvalRequestable: false,
    endpoint: '/api/actions/execute',
    summary: 'Reads truthful Shopify connection state, plan, and product counts. Missing credentials return disconnected.',
    requirements: ['signed-in user', 'server-side credential lookup', 'no fake connected state'],
    externalAction: false
  },
  {
    actionType: 'shopify_product_create',
    toolName: 'shopify_product_create',
    label: 'Create Shopify product',
    category: 'Business/POD',
    status: 'active',
    approvalRequired: true,
    approvalRequestable: true,
    endpoint: '/api/actions/execute',
    summary: 'Creates or prepares an approved Shopify draft product from a ready GFXTools asset and selected fulfillment provider.',
    requirements: ['approved product preview', 'ready GFX asset with platform variants', 'selected provider', 'server-side Shopify connector check'],
    externalAction: true
  },
  {
    actionType: 'shopify_product_publish',
    toolName: 'shopify_product_publish',
    label: 'Publish Shopify product',
    category: 'Business/POD',
    status: 'active',
    approvalRequired: true,
    approvalRequestable: true,
    endpoint: '/api/actions/execute',
    summary: 'Moves an approved product from draft to active and emits product_published for the social pipeline.',
    requirements: ['approved publish preview', 'existing user-owned product', 'audit log'],
    externalAction: true
  },
  {
    actionType: 'shopify_product_update',
    toolName: 'shopify_product_update',
    label: 'Update Shopify product',
    category: 'Business/POD',
    status: 'active',
    approvalRequired: true,
    approvalRequestable: true,
    endpoint: '/api/actions/execute',
    summary: 'Updates a product only after showing a diff/preview card.',
    requirements: ['approved diff preview', 'existing user-owned product', 'audit log'],
    externalAction: true
  },
  {
    actionType: 'shopify_product_archive',
    toolName: 'shopify_product_archive',
    label: 'Archive Shopify product',
    category: 'Business/POD',
    status: 'active',
    approvalRequired: true,
    approvalRequestable: true,
    endpoint: '/api/actions/execute',
    summary: 'Archives a product after an irreversible-action approval card.',
    requirements: ['approved irreversible archive preview', 'existing user-owned product', 'audit log'],
    externalAction: true
  },
  {
    actionType: 'fulfilment_provider_read',
    toolName: 'fulfilment_provider_read',
    label: 'Fulfilment providers',
    category: 'Business/POD',
    status: 'read_only',
    approvalRequired: false,
    approvalRequestable: false,
    endpoint: '/api/actions/execute',
    summary: 'Reads the POD provider manifest. Shopify-app providers are routing-only; direct API providers require server-side connectors.',
    requirements: ['signed-in user', 'no direct calls for Shopify-app providers', 'no fake provider status'],
    externalAction: false
  },
  {
    actionType: 'pod_provider_connect',
    toolName: 'pod_provider_connect',
    label: 'Connect POD provider',
    category: 'Business/POD',
    status: 'active',
    approvalRequired: true,
    approvalRequestable: true,
    endpoint: '/api/actions/execute',
    summary: 'Stores Printify, Printful, Gelato, or AfterShip API credentials server-side only.',
    requirements: ['signed-in user', 'approved connector preview', 'server-side encryption key'],
    externalAction: false
  },
  {
    actionType: 'design_create',
    toolName: 'design_create',
    label: 'Create provider design',
    category: 'Business/POD',
    status: 'active',
    approvalRequired: true,
    approvalRequestable: true,
    endpoint: '/api/actions/execute',
    summary: 'Submits a ready GFXTools asset to Printify, Printful, or Gelato when that direct connector is configured.',
    requirements: ['approved provider design preview', 'ready asset', 'direct provider credentials', 'audit log'],
    externalAction: true
  },
  {
    actionType: 'product_sync',
    toolName: 'product_sync',
    label: 'Sync provider product',
    category: 'Business/POD',
    status: 'active',
    approvalRequired: true,
    approvalRequestable: true,
    endpoint: '/api/actions/execute',
    summary: 'Prepares provider-to-Shopify sync after a design is ready. Missing provider ids block truthfully.',
    requirements: ['approved sync preview', 'provider design record', 'audit log'],
    externalAction: true
  },
  {
    actionType: 'provider_product_status',
    toolName: 'provider_product_status',
    label: 'Provider product status',
    category: 'Business/POD',
    status: 'read_only',
    approvalRequired: false,
    approvalRequestable: false,
    endpoint: '/api/actions/execute',
    summary: 'Reads user-owned provider design/product state without mutating providers.',
    requirements: ['signed-in user'],
    externalAction: false
  },
  {
    actionType: 'shopify_collection_create',
    toolName: 'shopify_collection_create',
    label: 'Create Shopify collection',
    category: 'Business/POD',
    status: 'active',
    approvalRequired: true,
    approvalRequestable: true,
    endpoint: '/api/actions/execute',
    summary: 'Creates a manual or smart collection payload after approval.',
    requirements: ['approved collection preview', 'audit log'],
    externalAction: true
  },
  {
    actionType: 'shopify_collection_assign',
    toolName: 'shopify_collection_assign',
    label: 'Assign collection',
    category: 'Business/POD',
    status: 'active',
    approvalRequired: true,
    approvalRequestable: true,
    endpoint: '/api/actions/execute',
    summary: 'Assigns a product to a collection after approval.',
    requirements: ['approved assignment preview', 'existing product and collection'],
    externalAction: true
  },
  {
    actionType: 'shopify_inventory_read',
    toolName: 'shopify_inventory_read',
    label: 'Inventory read',
    category: 'Business/POD',
    status: 'read_only',
    approvalRequired: false,
    approvalRequestable: false,
    endpoint: '/api/actions/execute',
    summary: 'Reads aggregate stock levels per variant without changing inventory.',
    requirements: ['signed-in user', 'no mutation'],
    externalAction: false
  },
  {
    actionType: 'shopify_inventory_update',
    toolName: 'shopify_inventory_update',
    label: 'Inventory update',
    category: 'Business/POD',
    status: 'active',
    approvalRequired: true,
    approvalRequestable: true,
    endpoint: '/api/actions/execute',
    summary: 'Records an approved before/after inventory adjustment.',
    requirements: ['approved before/after preview', 'audit log'],
    externalAction: true
  },
  {
    actionType: 'shopify_orders_read',
    toolName: 'shopify_orders_read',
    label: 'Orders read',
    category: 'Business/POD',
    status: 'read_only',
    approvalRequired: false,
    approvalRequestable: false,
    endpoint: '/api/actions/execute',
    summary: 'Reads open, fulfilled, and cancelled order aggregates only. No raw customer PII is stored.',
    requirements: ['signed-in user', 'aggregate-only storage'],
    externalAction: false
  },
  {
    actionType: 'shopify_order_summary',
    toolName: 'shopify_order_summary',
    label: 'Order summary',
    category: 'Business/POD',
    status: 'read_only',
    approvalRequired: false,
    approvalRequestable: false,
    endpoint: '/api/actions/execute',
    summary: 'Creates a daily-report-ready order summary with revenue, fulfilment rate, and top products.',
    requirements: ['signed-in user', 'no raw customer PII'],
    externalAction: false
  },
  {
    actionType: 'aftership_connect',
    toolName: 'aftership_connect',
    label: 'Connect AfterShip',
    category: 'Business/POD',
    status: 'active',
    approvalRequired: true,
    approvalRequestable: true,
    endpoint: '/api/actions/execute',
    summary: 'Stores AfterShip API credentials server-side only for read-only tracking and returns.',
    requirements: ['approved connector preview', 'server-side encryption key'],
    externalAction: false
  },
  {
    actionType: 'aftership_tracking_read',
    toolName: 'aftership_tracking_read',
    label: 'AfterShip tracking',
    category: 'Business/POD',
    status: 'read_only',
    approvalRequired: false,
    approvalRequestable: false,
    endpoint: '/api/actions/execute',
    summary: 'Reads tracking status snapshots for dashboard and daily report.',
    requirements: ['signed-in user', 'read-only'],
    externalAction: false
  },
  {
    actionType: 'aftership_returns_read',
    toolName: 'aftership_returns_read',
    label: 'AfterShip returns',
    category: 'Business/POD',
    status: 'read_only',
    approvalRequired: false,
    approvalRequestable: false,
    endpoint: '/api/actions/execute',
    summary: 'Reads open returns status for dashboard and daily report. No return mutation in V2.',
    requirements: ['signed-in user', 'read-only'],
    externalAction: false
  },
  {
    actionType: 'shopify_analytics_read',
    toolName: 'shopify_analytics_read',
    label: 'Shopify analytics',
    category: 'Business/POD',
    status: 'read_only',
    approvalRequired: false,
    approvalRequestable: false,
    endpoint: '/api/actions/execute',
    summary: 'Reads aggregate revenue, sessions, conversion, and top product metrics only.',
    requirements: ['signed-in user', 'aggregate-only storage'],
    externalAction: false
  },
  {
    actionType: 'shopify_bundles_read',
    toolName: 'shopify_bundles_read',
    label: 'Bundles read',
    category: 'Business/POD',
    status: 'read_only',
    approvalRequired: false,
    approvalRequestable: false,
    endpoint: '/api/actions/execute',
    summary: 'Lists active bundle configurations without mutation.',
    requirements: ['signed-in user'],
    externalAction: false
  },
  {
    actionType: 'shopify_bundle_create',
    toolName: 'shopify_bundle_create',
    label: 'Create bundle',
    category: 'Business/POD',
    status: 'active',
    approvalRequired: true,
    approvalRequestable: true,
    endpoint: '/api/actions/execute',
    summary: 'Creates a bundle from existing products after showing contents and pricing.',
    requirements: ['approved bundle preview', 'existing product ids', 'audit log'],
    externalAction: true
  },
  {
    actionType: 'marketplace_status_read',
    toolName: 'marketplace_status_read',
    label: 'Marketplace status',
    category: 'Business/POD',
    status: 'read_only',
    approvalRequired: false,
    approvalRequestable: false,
    endpoint: '/api/actions/execute',
    summary: 'Reads Amazon, eBay, Walmart Marketplace Connect status only. No marketplace mutation in V2.',
    requirements: ['signed-in user', 'read-only'],
    externalAction: false
  },
  {
    actionType: 'social_connector_status',
    toolName: 'social_connector_status',
    label: 'Social connector status',
    category: 'Social/Affiliate',
    status: 'read_only',
    approvalRequired: false,
    approvalRequestable: false,
    endpoint: '/api/actions/execute',
    summary: 'Read-only server-side social platform connector state. Missing credentials return disconnected and never fake connected.',
    requirements: ['server-side credential check only', 'no frontend key exposure', 'no fake connected state'],
    externalAction: false
  },
  {
    actionType: 'social_post_prepare',
    toolName: 'social_post_prepare',
    label: 'Social post prepare',
    category: 'Social/Affiliate',
    status: 'active',
    approvalRequired: true,
    approvalRequestable: true,
    endpoint: '/api/actions/execute',
    summary: 'Creates platform-aware social draft variants from an approved asset and stores them in user-owned Supabase state.',
    requirements: ['signed-in user', 'approved social_post_prepare approval', 'image/video URL or GFXTools output asset', 'platform-aware preview card'],
    externalAction: false
  },
  {
    actionType: 'social_post_schedule_approved',
    toolName: 'social_post_schedule_approved',
    label: 'Schedule social post',
    category: 'Social/Affiliate',
    status: 'active',
    approvalRequired: true,
    approvalRequestable: true,
    endpoint: '/api/actions/execute',
    summary: 'Creates an approved, user-configurable distribution rule and scheduled post rows. Missing platform credentials block firing instead of faking connection.',
    requirements: ['signed-in user', 'approved social_post_schedule_approved approval', 'full platform content preview', 'cadence preview', 'connector status check'],
    externalAction: true
  },
  {
    actionType: 'camera_permission_check',
    toolName: 'camera_permission_check',
    label: 'Camera permission check',
    category: 'Sensors/Auth',
    status: 'read_only',
    approvalRequired: false,
    approvalRequestable: false,
    endpoint: '/api/actions/capabilities',
    summary: 'Permission state must remain browser/platform controlled. No camera read occurs here.',
    requirements: ['browser permission prompt before any camera context'],
    externalAction: false
  },
  {
    actionType: 'camera_context_read',
    toolName: 'camera_context_read',
    label: 'Camera context read',
    category: 'Sensors/Auth',
    status: 'locked',
    approvalRequired: true,
    approvalRequestable: false,
    endpoint: null,
    summary: 'Locked until explicit camera permission, visible sensor indicator, and retention controls exist.',
    requirements: ['camera permission UI', 'active sensor indicator', 'session-only mode', 'retention controls'],
    externalAction: true
  },
  {
    actionType: 'coder_write_approved',
    toolName: 'coder_write_approved',
    label: 'Coder write approved',
    category: 'Coder/Studio',
    status: 'locked',
    approvalRequired: true,
    approvalRequestable: false,
    endpoint: null,
    summary: 'Locked until managed sandbox/API execution replaces custom raw terminal access.',
    requirements: ['managed sandbox/API', 'patch preview', 'allowlisted commands', 'approval card', 'audit log'],
    externalAction: true
  }
];

export const ACTION_TYPES = V2_CAPABILITIES.map(capability => capability.actionType) as string[];

export const FOUNDATION_ACTION_TYPES = V2_CAPABILITIES
  .filter(capability => capability.status === 'active' && capability.approvalRequestable)
  .map(capability => capability.actionType) as string[];

export function getActionCapability(actionType: string | null | undefined) {
  return V2_CAPABILITIES.find(capability => capability.actionType === actionType) || null;
}

export function isApprovalRequestable(actionType: string) {
  return Boolean(getActionCapability(actionType)?.approvalRequestable);
}
