/**
 * Type definitions for the Adaptive Learning system
 * ML-inspired user modeling for personalized CubiQo experiences
 */

/** Tracked interaction categories for behavior modeling */
export type InteractionCategory =
  | 'casual'       // General chat, small talk
  | 'emotional'    // Emotional sharing, vulnerable moments
  | 'intellectual' // Deep questions, analytical topics
  | 'creative'     // Creative discussions, brainstorming
  | 'goal'         // Goal-setting, productivity
  | 'intimate'     // Personal/intimate conversations

/** Time-of-day slots for temporal pattern analysis */
export type TimeSlot = 'morning' | 'afternoon' | 'evening' | 'night'

/** Engagement level classification */
export type EngagementLevel = 'low' | 'medium' | 'high' | 'deep'

/**
 * Single interaction data point for learning
 */
export interface InteractionSignal {
  category: InteractionCategory
  color: string
  messageLength: number
  responseEngagement: EngagementLevel
  timestamp: string
  timeSlot: TimeSlot
  usedVoice: boolean
  sessionDuration?: number // seconds
}

/**
 * Aggregated behavior weights for user preference modeling
 * Values are 0-1 scores derived from interaction history
 */
export interface BehaviorWeights {
  categoryPreferences: Record<InteractionCategory, number>
  colorAffinities: Record<string, number>
  voicePreference: number       // 0 = text-only, 1 = strong voice preference
  engagementDepth: number       // 0 = surface, 1 = deep conversations
  averageMessageLength: number
  peakTimeSlots: Record<TimeSlot, number>
  conversationFrequency: number // sessions per week (estimated)
  adaptationScore: number       // how much the user has been adapted to (0-1)
}

/**
 * User model combining learned behavior with explicit preferences
 */
export interface UserAdaptiveModel {
  userId: string
  weights: BehaviorWeights
  totalInteractions: number
  firstSeenAt: string
  lastSeenAt: string
  learningRate: number         // Decay factor for new vs old signals (0-1)
  version: number              // Model version for migrations
}

/**
 * Adaptation recommendations generated by the engine
 */
export interface AdaptationRecommendation {
  promptModifiers: string[]       // Additional instructions for system prompt
  suggestedColor: string | null   // Suggested starting color based on patterns
  voiceEncouragement: boolean     // Whether to encourage voice usage
  conversationStyle: 'brief' | 'moderate' | 'elaborate'
  engagementStrategy: 'nurturing' | 'challenging' | 'supportive' | 'playful'
}

/**
 * Default behavior weights for new users
 */
export const DEFAULT_BEHAVIOR_WEIGHTS: BehaviorWeights = {
  categoryPreferences: {
    casual: 0.5,
    emotional: 0.3,
    intellectual: 0.3,
    creative: 0.3,
    goal: 0.3,
    intimate: 0.1,
  },
  colorAffinities: {
    ORANGE: 0.4,
    YELLOW: 0.3,
    GREEN_BLUE: 0.2,
    RED: 0.1,
  },
  voicePreference: 0.5,
  engagementDepth: 0.5,
  averageMessageLength: 50,
  peakTimeSlots: {
    morning: 0.25,
    afternoon: 0.25,
    evening: 0.25,
    night: 0.25,
  },
  conversationFrequency: 0,
  adaptationScore: 0,
}
