/**
 * Multimodal AI Type Definitions
 * Shared types for vision, audio, and multimodal coordination
 */

// ============================================================================
// VISION TYPES
// ============================================================================

export interface ObjectDetection {
  /** Object label (e.g., "laptop", "coffee cup") */
  label: string;
  
  /** Confidence score (0-1) */
  confidence: number;
  
  /** Bounding box coordinates */
  bbox: BoundingBox;
  
  /** Optional: Object class ID */
  classId?: number;
}

export interface FaceDetection {
  /** Confidence score (0-1) */
  confidence: number;
  
  /** Bounding box coordinates */
  bbox: BoundingBox;
  
  /** Optional: Facial landmarks (eyes, nose, mouth) */
  landmarks?: Landmark[];
  
  /** Optional: Face attributes (age, gender, emotion - future) */
  attributes?: FaceAttributes;
}

export interface BoundingBox {
  x: number;
  y: number;
  width: number;
  height: number;
}

export interface Landmark {
  x: number;
  y: number;
  label?: string; // e.g., "left_eye", "nose", "mouth"
}

export interface FaceAttributes {
  age?: number;
  gender?: 'male' | 'female' | 'unknown';
  emotion?: EmotionType;
}

export interface ProcessedFrame {
  /** Timestamp when frame was captured */
  timestamp: number;
  
  /** Raw image data */
  imageData: ImageData;
  
  /** Frame dimensions */
  width: number;
  height: number;
  
  /** Optional: Base64-encoded image (for API calls) */
  base64?: string;
}

export interface VisionResult {
  /** Detected objects in frame */
  objects: ObjectDetection[];
  
  /** Detected faces in frame */
  faces: FaceDetection[];
  
  /** Optional: Scene description (generated by AI) */
  sceneDescription?: string;
  
  /** Processing timestamp */
  timestamp: number;
}

// ============================================================================
// AUDIO TYPES
// ============================================================================

export interface AudioFeatures {
  /** Volume level (0-100) */
  volume: number;
  
  /** Pitch in Hz */
  pitch: number;
  
  /** Estimated speech cadence (words per minute) */
  cadence: number;
  
  /** Signal energy (RMS) */
  energy: number;
  
  /** Timestamp of analysis */
  timestamp: number;
  
  /** Optional: Frequency spectrum data */
  frequencyData?: Uint8Array;
}

export type EmotionType = 
  | 'neutral'
  | 'happy'
  | 'sad'
  | 'angry'
  | 'excited'
  | 'calm'
  | 'fearful'
  | 'disgusted'
  | 'surprised';

export interface EmotionState {
  /** Primary detected emotion */
  primary: EmotionType;
  
  /** Confidence score (0-1) */
  confidence: number;
  
  /** Emotional valence: positive/negative (-1 to 1) */
  valence: number;
  
  /** Arousal level: energy/activation (0 to 1) */
  arousal: number;
  
  /** Optional: Secondary emotions with scores */
  secondary?: Array<{
    emotion: EmotionType;
    confidence: number;
  }>;
  
  /** Timestamp of analysis */
  timestamp: number;
}

// ============================================================================
// MULTIMODAL TYPES
// ============================================================================

export interface MultimodalContext {
  /** Timestamp when context was captured */
  timestamp: number;
  
  /** Vision context (if enabled) */
  vision?: {
    objects: ObjectDetection[];
    faces: FaceDetection[];
    sceneDescription?: string;
  };
  
  /** Audio context (if enabled) */
  audio?: {
    emotion: EmotionState;
    features: AudioFeatures;
  };
  
  /** Fused user state (derived from vision + audio) */
  userState?: UserState;
  
  /** Session metadata */
  metadata?: {
    visionEnabled: boolean;
    audioEnabled: boolean;
    processingLatency?: number;
  };
}

export interface UserState {
  /** User engagement level */
  engagement: 'low' | 'medium' | 'high';
  
  /** Overall mood assessment */
  mood: string;
  
  /** Attention state */
  attention: 'focused' | 'distracted' | 'unknown';
  
  /** Optional: Activity detection (future) */
  activity?: 'sitting' | 'standing' | 'moving' | 'unknown';
}

export interface EnhancedPrompt {
  /** Original user message */
  originalText: string;
  
  /** Enhanced text with multimodal context */
  enhancedText: string;
  
  /** System context to inject into LLM */
  systemContext: string;
  
  /** Additional metadata for AI router */
  metadata: {
    hasVision: boolean;
    hasAudio: boolean;
    emotionDetected?: EmotionType;
    objectsDetected?: string[];
  };
}

// ============================================================================
// CONFIGURATION TYPES
// ============================================================================

export interface MultimodalConfig {
  /** Enable/disable vision processing */
  vision: {
    enabled: boolean;
    
    /** Object detection settings */
    objectDetection: {
      enabled: boolean;
      confidenceThreshold: number;
      maxDetections: number;
    };
    
    /** Face detection settings */
    faceDetection: {
      enabled: boolean;
      confidenceThreshold: number;
    };
    
    /** Frame processing rate (frames per second) */
    processingFPS: number;
    
    /** Camera facing mode */
    facingMode: 'user' | 'environment';
  };
  
  /** Enable/disable audio analysis */
  audio: {
    enabled: boolean;
    
    /** Emotion detection settings */
    emotionDetection: {
      enabled: boolean;
      provider: 'web-audio' | 'hume-ai' | 'azure';
    };
    
    /** Audio analysis rate (samples per second) */
    analysisRate: number;
  };
  
  /** Multimodal coordination settings */
  coordination: {
    /** Fuse vision + audio into user state */
    fuseUserState: boolean;
    
    /** Include multimodal context in AI prompts */
    enhancePrompts: boolean;
  };
}

// ============================================================================
// PERMISSION TYPES
// ============================================================================

export type PermissionState = 'granted' | 'denied' | 'prompt';

export interface MediaPermissions {
  camera: PermissionState;
  microphone: PermissionState;
}

// ============================================================================
// ERROR TYPES
// ============================================================================

export class MultimodalError extends Error {
  constructor(
    message: string,
    public code: MultimodalErrorCode,
    public details?: unknown
  ) {
    super(message);
    this.name = 'MultimodalError';
  }
}

export type MultimodalErrorCode =
  | 'CAMERA_PERMISSION_DENIED'
  | 'MICROPHONE_PERMISSION_DENIED'
  | 'CAMERA_NOT_AVAILABLE'
  | 'MODEL_LOAD_FAILED'
  | 'PROCESSING_ERROR'
  | 'UNSUPPORTED_BROWSER'
  | 'NETWORK_ERROR';

// ============================================================================
// ADDITIONAL TYPE ALIASES FOR COMPATIBILITY
// ============================================================================

export type CameraType = 'front' | 'back';
export type VisionDetection = ObjectDetection;
export type CameraPermissionState = { granted: boolean; denied: boolean; prompt: boolean };
export type MicrophonePermissionState = { granted: boolean; denied: boolean; prompt: boolean };

// ============================================================================
// HOOK RETURN TYPES
// ============================================================================

export interface UseCameraReturn {
  stream: MediaStream | null;
  permission: PermissionState;
  error: Error | null;
  facingMode: 'user' | 'environment';
  startCamera: () => Promise<void>;
  stopCamera: () => void;
  switchCamera: () => Promise<void>;
}

export interface UseVisionReturn {
  detections: VisionResult | null;
  processing: boolean;
  error: Error | null;
}

export interface UseEmotionDetectionReturn {
  emotion: EmotionState | null;
  features: AudioFeatures | null;
  error: Error | null;
}

export interface UseMultimodalAIReturn {
  // Camera controls
  startCamera: () => Promise<void>;
  stopCamera: () => void;
  switchCamera: () => Promise<void>;
  
  // Real-time data
  detections: VisionResult | null;
  emotion: EmotionState | null;
  
  // Multimodal context
  getContext: () => Promise<MultimodalContext>;
  getEnhancedPrompt: (message: string) => Promise<EnhancedPrompt>;
  
  // State
  visionEnabled: boolean;
  audioEnabled: boolean;
  isProcessing: boolean;
  error: Error | null;
}

// ============================================================================
// EVENT TYPES
// ============================================================================

export type MultimodalEvent =
  | { type: 'camera_started'; stream: MediaStream }
  | { type: 'camera_stopped' }
  | { type: 'permission_denied'; permission: 'camera' | 'microphone' }
  | { type: 'detection_complete'; result: VisionResult }
  | { type: 'emotion_detected'; emotion: EmotionState }
  | { type: 'error'; error: MultimodalError };

export type MultimodalEventHandler = (event: MultimodalEvent) => void;

// ============================================================================
// ANALYTICS TYPES
// ============================================================================

export interface MultimodalAnalytics {
  /** Session ID */
  sessionId: string;
  
  /** Feature usage */
  usage: {
    visionEnabled: boolean;
    audioEnabled: boolean;
    sessionDuration: number;
    framesCaptured: number;
    emotionsDetected: number;
  };
  
  /** Performance metrics */
  performance: {
    avgProcessingLatency: number;
    avgFPS: number;
    modelLoadTime: number;
  };
  
  /** Accuracy metrics */
  accuracy?: {
    objectDetectionConfidence: number;
    faceDetectionConfidence: number;
    emotionConfidence: number;
  };
}

// All types are already exported above via their declarations
