/**
 * Staging Readiness Report
 *
 * Checks all open PRs in thecubiqo/thecubiqo and evaluates whether they are
 * ready to be merged into the staging branch.
 *
 * Readiness criteria per PR:
 *   1. No active Copilot agent runs (agent work is complete)
 *   2. CI checks are green
 *   3. No merge conflicts
 *   4. PR is not a draft
 *
 * When every open PR passes all criteria the report declares the repository
 * "staging-ready".
 *
 * Usage:
 *   GITHUB_TOKEN=<token> tsx scripts/staging-readiness-report.ts
 */

import { Octokit } from "@octokit/rest";
import fs from "fs";
import path from "path";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface PRReadiness {
  number: number;
  title: string;
  url: string;
  author: string;
  isDraft: boolean;
  ciGreen: boolean;
  ciDetail: string;
  mergeable: boolean | null;
  agentActive: boolean;
  agentDetail: string;
  ready: boolean;
}

export interface ReadinessReport {
  timestamp: string;
  owner: string;
  repo: string;
  totalOpen: number;
  readyCount: number;
  notReadyCount: number;
  allAgentsDone: boolean;
  stagingReady: boolean;
  prs: PRReadiness[];
}

// ---------------------------------------------------------------------------
// Pure helpers (exported for unit testing)
// ---------------------------------------------------------------------------

/** Determine if a workflow run name looks like a Copilot agent run. */
export function isAgentRun(runName: string): boolean {
  const lower = runName.toLowerCase();
  return (
    lower.includes("copilot") ||
    lower.includes("agent") ||
    lower.includes("bot")
  );
}

/** Determine if a workflow run is still in progress. */
export function isRunInProgress(status: string): boolean {
  return status === "queued" || status === "in_progress" || status === "waiting";
}

/** Compute per-PR readiness from individual signals. */
export function computeReadiness(pr: {
  isDraft: boolean;
  ciGreen: boolean;
  mergeable: boolean | null;
  agentActive: boolean;
}): boolean {
  return !pr.isDraft && pr.ciGreen && pr.mergeable === true && !pr.agentActive;
}

/** Build the overall staging-readiness flag. */
export function computeStagingReady(prs: PRReadiness[]): boolean {
  if (prs.length === 0) return true;
  return prs.every((pr) => pr.ready);
}

/** Format a markdown report from the structured data. */
export function formatMarkdownReport(report: ReadinessReport): string {
  const lines: string[] = [];

  lines.push("# Staging Readiness Report");
  lines.push("");
  lines.push(`**Repository:** ${report.owner}/${report.repo}`);
  lines.push(`**Generated:** ${report.timestamp}`);
  lines.push("");

  // Overall verdict
  if (report.stagingReady) {
    lines.push("## ✅ Staging Ready");
    lines.push("");
    lines.push(
      "All agents have finished and every open PR meets the readiness criteria."
    );
    lines.push("It is safe to merge all open PRs into staging.");
  } else {
    lines.push("## ❌ Not Yet Staging Ready");
    lines.push("");
    if (!report.allAgentsDone) {
      lines.push(
        "⏳ **Agents are still working.** Wait for all agent runs to complete before merging."
      );
    }
    if (report.notReadyCount > 0) {
      lines.push(
        `⚠️ **${report.notReadyCount} PR(s)** do not meet the readiness criteria.`
      );
    }
  }

  lines.push("");
  lines.push("## Summary");
  lines.push("");
  lines.push(`- **Open PRs:** ${report.totalOpen}`);
  lines.push(`- **Ready:** ${report.readyCount}`);
  lines.push(`- **Not Ready:** ${report.notReadyCount}`);
  lines.push(`- **All Agents Done:** ${report.allAgentsDone ? "Yes" : "No"}`);
  lines.push("");

  // Per-PR table
  lines.push("## PR Details");
  lines.push("");
  lines.push(
    "| PR | Title | Draft | CI | Conflicts | Agent Active | Ready |"
  );
  lines.push(
    "|----|-------|-------|----|-----------|--------------|-------|"
  );

  for (const pr of report.prs) {
    const draft = pr.isDraft ? "Yes" : "No";
    const ci = pr.ciGreen ? "✅" : "❌";
    const conflicts =
      pr.mergeable === true ? "None" : pr.mergeable === false ? "Yes" : "Unknown";
    const agent = pr.agentActive ? "⏳ Yes" : "✅ No";
    const ready = pr.ready ? "✅" : "❌";

    lines.push(
      `| [#${pr.number}](${pr.url}) | ${pr.title} | ${draft} | ${ci} | ${conflicts} | ${agent} | ${ready} |`
    );
  }

  lines.push("");
  lines.push(
    "---\n\n*Generated by `scripts/staging-readiness-report.ts`*"
  );

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// GitHub API helpers (only executed when running as a script)
// ---------------------------------------------------------------------------

async function checkCi(
  octokit: Octokit,
  owner: string,
  repo: string,
  ref: string
): Promise<{ green: boolean; detail: string }> {
  try {
    const { data: combined } = await octokit.repos.getCombinedStatusForRef({
      owner,
      repo,
      ref,
    });

    const { data: checkRuns } = await octokit.checks.listForRef({
      owner,
      repo,
      ref,
      per_page: 100,
    });

    const statusOk =
      combined.state === "success" || combined.statuses.length === 0;

    const checksOk = checkRuns.check_runs.every(
      (cr) => cr.conclusion === "success" || cr.conclusion === "skipped"
    );

    const allGreen = statusOk && checksOk;

    const failed = [
      ...combined.statuses
        .filter((s) => s.state !== "success")
        .map((s) => s.context),
      ...checkRuns.check_runs
        .filter(
          (cr) => cr.conclusion !== "success" && cr.conclusion !== "skipped"
        )
        .map((cr) => cr.name),
    ];

    return {
      green: allGreen,
      detail: allGreen
        ? "All checks passed"
        : `Failed/pending: ${failed.join(", ") || combined.state}`,
    };
  } catch {
    return { green: false, detail: "Unable to retrieve CI status" };
  }
}

async function checkAgentActivity(
  octokit: Octokit,
  owner: string,
  repo: string,
  headBranch: string
): Promise<{ active: boolean; detail: string }> {
  try {
    const { data } = await octokit.actions.listWorkflowRunsForRepo({
      owner,
      repo,
      branch: headBranch,
      per_page: 20,
    });

    const activeAgentRuns = data.workflow_runs.filter(
      (run) =>
        isAgentRun(run.name ?? "") && isRunInProgress(run.status ?? "")
    );

    if (activeAgentRuns.length > 0) {
      return {
        active: true,
        detail: `${activeAgentRuns.length} agent run(s) still in progress`,
      };
    }

    return { active: false, detail: "No active agent runs" };
  } catch {
    return { active: false, detail: "Unable to check agent activity" };
  }
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function run(): Promise<void> {
  const GITHUB_TOKEN = process.env.GITHUB_TOKEN;
  if (!GITHUB_TOKEN) {
    console.error("Error: GITHUB_TOKEN environment variable is required.");
    process.exit(1);
  }

  const OWNER = process.env.READINESS_OWNER ?? "thecubiqo";
  const REPO = process.env.READINESS_REPO ?? "thecubiqo";
  const OUTPUT_DIR = "REPORTS";
  const OUTPUT_FILE = "STAGING_READINESS.md";

  const octokit = new Octokit({ auth: GITHUB_TOKEN });

  console.log(`\n📋 Staging Readiness Report — ${OWNER}/${REPO}\n`);

  // Fetch all open PRs
  const { data: pullRequests } = await octokit.pulls.list({
    owner: OWNER,
    repo: REPO,
    state: "open",
    per_page: 100,
  });

  if (pullRequests.length === 0) {
    console.log("No open PRs found. Staging is ready by default.\n");
  }

  console.log(`Found ${pullRequests.length} open PR(s).\n`);

  const prs: PRReadiness[] = [];

  for (const pr of pullRequests) {
    process.stdout.write(`Checking PR #${pr.number}… `);

    // Fetch full PR for mergeable status
    const { data: fullPr } = await octokit.pulls.get({
      owner: OWNER,
      repo: REPO,
      pull_number: pr.number,
    });

    const ci = await checkCi(octokit, OWNER, REPO, fullPr.head.sha);
    const agent = await checkAgentActivity(
      octokit,
      OWNER,
      REPO,
      fullPr.head.ref
    );

    const prReadiness: PRReadiness = {
      number: pr.number,
      title: pr.title,
      url: fullPr.html_url,
      author: pr.user?.login ?? "unknown",
      isDraft: fullPr.draft ?? false,
      ciGreen: ci.green,
      ciDetail: ci.detail,
      mergeable: fullPr.mergeable,
      agentActive: agent.active,
      agentDetail: agent.detail,
      ready: false, // computed below
    };

    prReadiness.ready = computeReadiness(prReadiness);
    prs.push(prReadiness);

    const icon = prReadiness.ready ? "✅" : "❌";
    console.log(`${icon} ${prReadiness.ready ? "ready" : "not ready"}`);

    // Small delay for rate limiting
    await new Promise((resolve) => setTimeout(resolve, 100));
  }

  const allAgentsDone = prs.every((pr) => !pr.agentActive);
  const readyCount = prs.filter((pr) => pr.ready).length;
  const notReadyCount = prs.length - readyCount;

  const report: ReadinessReport = {
    timestamp: new Date().toISOString(),
    owner: OWNER,
    repo: REPO,
    totalOpen: prs.length,
    readyCount,
    notReadyCount,
    allAgentsDone,
    stagingReady: computeStagingReady(prs),
    prs,
  };

  // Write report
  if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  }

  const markdown = formatMarkdownReport(report);
  const outputPath = path.join(OUTPUT_DIR, OUTPUT_FILE);
  fs.writeFileSync(outputPath, markdown, "utf-8");

  // Console summary
  console.log("\n═══════════════════════════════════════════════════════");
  console.log("  Staging Readiness Summary");
  console.log("═══════════════════════════════════════════════════════\n");
  console.log(`  Open PRs:        ${report.totalOpen}`);
  console.log(`  Ready:           ${report.readyCount}`);
  console.log(`  Not Ready:       ${report.notReadyCount}`);
  console.log(`  All Agents Done: ${report.allAgentsDone ? "Yes" : "No"}`);
  console.log(`  Staging Ready:   ${report.stagingReady ? "✅ YES" : "❌ NO"}`);
  console.log(`\n📄 Full report saved to: ${outputPath}\n`);

  // Exit with non-zero if not staging-ready (useful for CI gating)
  if (!report.stagingReady) {
    process.exit(1);
  }
}

run().catch((err) => {
  console.error("Staging Readiness Report failed:", err);
  process.exit(1);
});
