/**
 * Email service for self-heal job reports
 * Uses Resend for email delivery
 */

import { Resend } from 'resend';

// Initialize Resend only if API key is available
let resend: Resend | null = null;
if (process.env.RESEND_API_KEY) {
  resend = new Resend(process.env.RESEND_API_KEY);
}

export interface EmailReport {
  timestamp: string;
  status: 'success' | 'partial' | 'failed';
  summary: {
    total_diagnostics: number;
    healthy: number;
    warnings: number;
    critical: number;
    fixes_applied: number;
    issues_found: number;
  };
  reportPath: string;
  rollbackPatchPath: string;
  signature: string;
}

/**
 * Format report as HTML email
 */
function formatReportEmail(report: EmailReport): string {
  const statusColor = 
    report.status === 'success' ? '#10b981' : 
    report.status === 'partial' ? '#f59e0b' : 
    '#ef4444';

  const statusEmoji = 
    report.status === 'success' ? '✅' : 
    report.status === 'partial' ? '⚠️' : 
    '❌';

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
      line-height: 1.6;
      color: #333;
      max-width: 600px;
      margin: 0 auto;
      padding: 20px;
    }
    .header {
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      color: white;
      padding: 30px;
      border-radius: 8px 8px 0 0;
      text-align: center;
    }
    .status {
      display: inline-block;
      background: ${statusColor};
      color: white;
      padding: 8px 16px;
      border-radius: 4px;
      font-weight: bold;
      margin: 10px 0;
    }
    .content {
      background: #f9fafb;
      padding: 30px;
      border-radius: 0 0 8px 8px;
    }
    .summary {
      background: white;
      padding: 20px;
      border-radius: 8px;
      margin: 20px 0;
      box-shadow: 0 1px 3px rgba(0,0,0,0.1);
    }
    .summary-item {
      display: flex;
      justify-content: space-between;
      padding: 8px 0;
      border-bottom: 1px solid #e5e7eb;
    }
    .summary-item:last-child {
      border-bottom: none;
    }
    .summary-label {
      font-weight: 600;
      color: #6b7280;
    }
    .summary-value {
      font-weight: 700;
      color: #111827;
    }
    .critical {
      color: #dc2626;
    }
    .warning {
      color: #f59e0b;
    }
    .healthy {
      color: #10b981;
    }
    .signature {
      background: #1f2937;
      color: #9ca3af;
      padding: 15px;
      border-radius: 4px;
      font-family: monospace;
      font-size: 12px;
      word-break: break-all;
      margin: 20px 0;
    }
    .footer {
      text-align: center;
      color: #6b7280;
      margin-top: 30px;
      padding-top: 20px;
      border-top: 1px solid #e5e7eb;
      font-size: 14px;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>${statusEmoji} CubiQo Self-Heal Report</h1>
    <div class="status">${report.status.toUpperCase()}</div>
    <p style="margin: 10px 0 0 0; opacity: 0.9;">
      ${new Date(report.timestamp).toLocaleString('en-US', { 
        dateStyle: 'full', 
        timeStyle: 'long' 
      })}
    </p>
  </div>

  <div class="content">
    <h2>Summary</h2>
    <div class="summary">
      <div class="summary-item">
        <span class="summary-label">Total Diagnostics</span>
        <span class="summary-value">${report.summary.total_diagnostics}</span>
      </div>
      <div class="summary-item">
        <span class="summary-label">Healthy</span>
        <span class="summary-value healthy">${report.summary.healthy}</span>
      </div>
      <div class="summary-item">
        <span class="summary-label">Warnings</span>
        <span class="summary-value warning">${report.summary.warnings}</span>
      </div>
      <div class="summary-item">
        <span class="summary-label">Critical Issues</span>
        <span class="summary-value critical">${report.summary.critical}</span>
      </div>
      <div class="summary-item">
        <span class="summary-label">Fixes Applied</span>
        <span class="summary-value">${report.summary.fixes_applied}</span>
      </div>
      <div class="summary-item">
        <span class="summary-label">Issues Found</span>
        <span class="summary-value">${report.summary.issues_found}</span>
      </div>
    </div>

    <h2>Artifacts</h2>
    <div class="summary">
      <div class="summary-item">
        <span class="summary-label">Report</span>
        <span class="summary-value" style="font-size: 12px;">${report.reportPath}</span>
      </div>
      <div class="summary-item">
        <span class="summary-label">Rollback Patch</span>
        <span class="summary-value" style="font-size: 12px;">${report.rollbackPatchPath}</span>
      </div>
    </div>

    <h2>Verification Signature</h2>
    <div class="signature">
      ${report.signature}
    </div>

    <p style="color: #6b7280; font-size: 14px; margin-top: 20px;">
      This report was automatically generated by the CubiQo self-heal system.
      The signature can be used to verify the authenticity of the report.
    </p>
  </div>

  <div class="footer">
    <p>CubiQo Self-Heal System</p>
    <p style="margin: 5px 0;">Automated Diagnostics & Maintenance</p>
  </div>
</body>
</html>
  `;
}

/**
 * Send self-heal report via email
 */
export async function sendSelfHealReport(
  report: EmailReport,
  recipient: string = 'aditya@cubiqo.ai'
): Promise<{ success: boolean; messageId?: string; error?: string }> {
  try {
    if (!resend || !process.env.RESEND_API_KEY) {
      
      return {
        success: false,
        error: 'RESEND_API_KEY not configured',
      };
    }

    const htmlContent = formatReportEmail(report);

    const statusEmoji = 
      report.status === 'success' ? '✅' : 
      report.status === 'partial' ? '⚠️' : 
      '❌';

    const response = await resend.emails.send({
      from: 'CubiQo Self-Heal <noreply@cubiqo.ai>',
      to: recipient,
      subject: `${statusEmoji} Self-Heal Report - ${report.status.toUpperCase()} - ${new Date(report.timestamp).toLocaleString()}`,
      html: htmlContent,
    });

    return {
      success: true,
      messageId: response.data?.id,
    };
  } catch (error) {
    
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    };
  }
}
